name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/large-project
            git pull origin main
            cd app/backend
            npm install
            pm2 restart backend

      - name: Notify Deployment Success
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{ secrets.DISCORD_TOKEN }}
          message: |
            **Deployment Successful to EC2!**
            **Message:** ${{ github.event.head_commit.message }}
            **Health Check:** [View System Health](http://${{ secrets.EC2_HOST }}/health)

      - name: Notify Deployment Failure
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_ID }}
          webhook_token: ${{ secrets.DISCORD_TOKEN }}
          message: |
            **Deployment Failed**
            **Message:** ${{ github.event.head_commit.message }}
            **Health Check:** [View System Health](http://${{ secrets.EC2_HOST }}/health)